_BASE_: "./OracleT-RCNN-FPN-CFC.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
AUG:
  INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: True
SOLVER:
  STEPS: (18000,)
  MAX_ITER: 20000
OUTPUT_DIR: "output/cfc/cfc_oraclet_strongaug_ema/"