_BASE_: "./OracleST-RCNN-VitDetB-CFC.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: True
SOLVER:
  STEPS: (18000,)
  MAX_ITER: 20000
OUTPUT_DIR: "output/cfc/cfc_vitdetb_oracle_st_strongaug_ema_mic/"