_BASE_: "./cityscapes_baseline/Base-RCNN-VitDetB-Cityscapes.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_vitdetb_baseline_foggy_val_model_best_1699.pth" 
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_CONTENTS: ("labeled_weak", "labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1,1)
DOMAIN_ADAPT:
  LOSSES:
    LOC_LOSS_ENABLED: False
  TEACHER:
    ENABLED: True
SOLVER:
  STEPS: (59999,)
  MAX_ITER: 60000
  BACKWARD_AT_END: False
OUTPUT_DIR: "output/cityscapes_vitdetb_meanteacher/"