_BASE_: "./OracleT-RCNN-FPN-Sim10k.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: True
OUTPUT_DIR: "output/sim10k/sim10k_oraclet_strongaug_ema/"