_BASE_: "../../Base-RCNN-VitDetB.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("cityscapes_cars_train",)
  TEST: ("cityscapes_cars_val",)
OUTPUT_DIR: "output/sim10k/sim10k_vitdetb_oracle_t/"