_BASE_: "../sim10k_baseline/Base-RCNN-FPN-Sim10k.yaml"
MODEL:
  META_ARCHITECTURE: "ALDI"
DOMAIN_ADAPT:
  ALIGN:
    IMG_DA_ENABLED: True
    IMG_DA_WEIGHT: 0.0025 # default of 0.01 diverges
DATASETS:
  UNLABELED: ("cityscapes_cars_train",)
  BATCH_CONTENTS: ("labeled_weak","unlabeled_weak")
  BATCH_RATIOS: (1,1)
OUTPUT_DIR: "output/sim10k_align_img/"