_BASE_: "../MeanTeacher-Cityscapes.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,0.5)
OUTPUT_DIR: "output/cityscapes_twothirdssourcestrong_onethirdtarget/"