_BASE_: "../cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
MODEL:
  DA:
    ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_CONTENTS: ("labeled_weak","unlabeled_weak")
  BATCH_RATIOS: (1,1)
SOLVER:
  BASE_LR: 0.01
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.0016 # roughly 1/625
  WARMUP_ITERS: 625
  CHECKPOINT_PERIOD: 6250
  BACKWARD_AT_END: False
VIS_PERIOD: 625
TEST:
  EVAL_PERIOD: 625
OUTPUT_DIR: "output/cityscapes_da_img/"