_BASE_: "./Base-RCNN-VitDetB-Sim10k.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
AUG:
  INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: True
OUTPUT_DIR: "output/sim10k/sim10k_vitdetb_baseline_strongaug_ema_mic/"

SOLVER:
  STEPS: (18000,)
  MAX_ITER: 24000
  CHECKPOINT_PERIOD: 3000