_BASE_: "../MeanTeacher-Cityscapes.yaml"
MODEL:
  SADA:
    ENABLED: True
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (100000,)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 6000
TEST:
  EVAL_PERIOD: 1250
OUTPUT_DIR: "output/cityscapes_meanteacher_sada_1gpu/"