_BASE_: "../MeanTeacher-Cityscapes.yaml"
DATASETS:
  INCLUDE_WEAK_IN_BATCH: False
  LABELED_STRONG_AUG: False
  INCLUDE_RANDOM_ERASING: False
  UNLABELED_MIC_AUG: True
DOMAIN_ADAPT:
  LOSSES:
    LOC_LOSS_ENABLED: False
    QUALITY_LOSS_WEIGHT_ENABLED: True
OUTPUT_DIR: "output/cityscapes_mic_no_sada/"