_BASE_: "../cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
MODEL:
  SADA:
    ENABLED: True
DATASETS:
  BATCH_CONTENTS: ("labeled_weak",)
  BATCH_RATIOS: (1,)
OUTPUT_DIR: "output/cityscapes_sada/"