_BASE_: "../MeanTeacher-Cityscapes.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,0.25)
OUTPUT_DIR: "output/cityscapes_fourfifthssourcestrong_onefifthtarget/"