_BASE_: "../MeanTeacher-Cityscapes.yaml"
MODEL:
  META_ARCHITECTURE: "ExtraRCNN"
  SADA:
    ENABLED: True
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
AUG:
  INCLUDE_RANDOM_ERASING: False
  UNLABELED_MIC_AUG: True
DOMAIN_ADAPT:
  LOSSES:
    QUALITY_LOSS_WEIGHT_ENABLED: True
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (149999,)
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 6000
TEST:
  EVAL_PERIOD: 1250
OUTPUT_DIR: "output/cityscapes_mic/"