_BASE_: "../MeanTeacher-Cityscapes.yaml"
MODEL:
  META_ARCHITECTURE: "ExtraRCNN"
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
AUG:
  INCLUDE_RANDOM_ERASING: False
  UNLABELED_MIC_AUG: True
DOMAIN_ADAPT:
  LOSSES:
    QUALITY_LOSS_WEIGHT_ENABLED: True
OUTPUT_DIR: "output/cityscapes_mic_no_sada/"