_BASE_: "./_Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_vgg_backbone"
  WEIGHTS: ""
  RPN:
    IN_FEATURES: ["vgg4"]
  ROI_HEADS:
    IN_FEATURES: ["vgg4"]
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (120000, 160000)
  MAX_ITER: 180000