_BASE_: "detectron2/Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "DARCNN"
  WEIGHTS: "models/model_final_f10217.pkl"
  MASK_ON: False
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
SOLVER:
  BASE_LR: 0.12
  STEPS: (2250,)
  MAX_ITER: 1500
  IMS_PER_BATCH: 96
  IMS_PER_GPU: 2
  AMP:
    ENABLED: True
  WARMUP_ITERS: 50
  WARMUP_FACTOR: 0.02
  # just save a few checkpoints throughout because we will also use BestCheckpointer
  # every TEST.EVAL_PERIOD
  CHECKPOINT_PERIOD: 500
VIS_PERIOD: 50
TEST:
  EVAL_PERIOD: 50 # ~one epoch for Cityscapes