_BASE_: "./Base-RCNN-FPN-Cityscapes.yaml"
DOMAIN_ADAPT:
  EMA:
    ENABLED: True
  TEACHER:
    ENABLED: True
  LOSSES:
    RPN_LOSS_ENABLED: False
  LABELED_STRONG_AUG: True
  UNLABELED_STRONG_AUG: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  LABELED_UNLABELED_RATIO: (1,1)
OUTPUT_DIR: "output/cityscapes_meanteacher/"