_BASE_: "./cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_baseline_foggy_val_model_best_519.pth" 
EMA:
  ENABLED: True
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  LABELED_UNLABELED_RATIO: (1,1)
  LABELED_STRONG_AUG: True
  UNLABELED_STRONG_AUG: True
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 8 # TODO: Had to reduce this when include_weak_in_batch was introduced
  STEPS: (90000,)
  MAX_ITER: 100000
TEST:
  EVAL_PERIOD: 625
OUTPUT_DIR: "output/cityscapes_meanteacher/"