_BASE_: "./cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
EMA:
  ENABLED: True
DOMAIN_ADAPT:
  TEACHER:
    ENABLED: True
  LOSSES:
    RPN_LOSS_ENABLED: False
DATASETS:
  UNLABELED: ("cityscapes_fine_instance_seg_train",) # FOR TESTING ("cityscapes_foggy_train",)
  LABELED_UNLABELED_RATIO: (1,1)
  LABELED_STRONG_AUG: True
  UNLABELED_STRONG_AUG: True
OUTPUT_DIR: "output/cityscapes_meanteacher/"