# this file mimics the settings of using "Mean Teacher" off the shelf with
# the Adaptive Teacher / Unbiased Teacher repo.
# that is:
# - batches are 1/3 weak source, 1/3 strong source, 1/3 target
# - bbox localization losses are disabled
# - random erasing is used as part of the strong augs

_BASE_: "./cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_baseline_foggy_val_model_best_519.pth" 
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  LABELED_UNLABELED_RATIO: (1,1)
  LABELED_STRONG_AUG: True
  UNLABELED_STRONG_AUG: True
  INCLUDE_WEAK_IN_BATCH: True
DOMAIN_ADAPT:
  LOSSES:
    LOC_LOSS_ENABLED: False
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  STEPS: (50000,)
  MAX_ITER: 60000
TEST:
  EVAL_PERIOD: 625
OUTPUT_DIR: "output/cityscapes_meanteacher/"