_BASE_: "./cityscapes_baseline/Probabilistic-RCNN-FPN-Cityscapes.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_baseline_foggy_val_model_best_519.pth" # TODO
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  LABELED_UNLABELED_RATIO: (1,1)
  LABELED_STRONG_AUG: True
  UNLABELED_STRONG_AUG: True
  INCLUDE_WEAK_IN_BATCH: True
GRCNN:
  LEARN_ANCHORS_LABELED: False
  LEARN_ANCHORS_UNLABELED: True
  EFL: True
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  STEPS: (50000,)
  MAX_ITER: 60000
TEST:
  EVAL_PERIOD: 625
OUTPUT_DIR: "output/cityscapes_probabilisticteacher/"