_BASE_: "../cityscapes_baseline/Base-RCNN-VitDetB-Cityscapes.yaml"
DATASETS:
  TRAIN: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_val","cityscapes_foggy_val",)
SOLVER:
  STEPS: (6400,)
  MAX_ITER: 8000
OUTPUT_DIR: "output/cityscapes_vitdetb_oracle-t/"