_BASE_: "../cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
DATASETS:
  TRAIN: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_val","cityscapes_foggy_val",)
OUTPUT_DIR: "output/cityscapes_oracle-t/"