_BASE_: "./Base-RCNN-FPN-CFC.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
AUG:
  INCLUDE_RANDOM_ERASING: False
  LABELED_MIC_AUG: True
OUTPUT_DIR: "output/cfc/cfc_baseline_strongaug_ema/"