_BASE_: "../../Probabilistic-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("cfc_train",)
  TEST: ("cfc_val", "cfc_channel_test",)
OUTPUT_DIR: "output/cfc/cfc_probabilistic_baseline/"

# rough numbers -- don't correspond to any specific number of epochs, just checking how we do
SOLVER:
  STEPS: (4600,)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 100