_BASE_: "../sim10k_baseline/Probabilistic-RCNN-FPN-Sim10k.yaml"
MODEL:
  META_ARCHITECTURE: "ExtraRCNN"
  WEIGHTS: "sim10_cityscapes_probabilistic_baseline_cityscapes_cars_val_model_best_687.pth"
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_cars_train",)
  BATCH_CONTENTS: ("labeled_weak", "labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1,1)
GRCNN:
  LEARN_ANCHORS_LABELED: False
  LEARN_ANCHORS_UNLABELED: True
  EFL: True
SOLVER:
  STEPS: (59999,)
  MAX_ITER: 60000
  BACKWARD_AT_END: False
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 10.0 # this mimics PT trainer
DOMAIN_ADAPT:
  TEACHER:
    PSEUDO_LABEL_METHOD: "probabilistic"

TEST:
  EVAL_PERIOD: 100

OUTPUT_DIR: "output/sim10k_probabilisticteacher/"